### ISSUE TITLE
Error when starting client

### ISSUE THREAD

**Issue by barthogenes** [MysteryCoder456/UrsinaFPS#4]
Hi, I get the following error when I try to start the game:
```
ursina version: 3.6.0
package_folder: C:\Users\Bart\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ursina
asset_folder: C:\Users\Bart\Documents\git\UrsinaFPS\game
blender_paths:
{'2.9': WindowsPath('C:/Program Files/Blender Foundation/Blender 2.92/blender.exe'),
 'default': WindowsPath('C:/Program Files/Blender Foundation/Blender 2.92/blender.exe')}
screen resolution: (1920, 1200)
Enter your username: bart
Enter server IP: localhost
Enter server port: 8000
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
:display:windisplay(warning): SetForegroundWindow() failed!
size; LVector2f(1536, 960)
render mode: default
no settings.py file
Traceback (most recent call last):
  File "C:\Users\Bart\Documents\git\UrsinaFPS\game\main.py", line 55, in <module>
    map = Map()
  File "C:\Users\Bart\Documents\git\UrsinaFPS\game\map.py", line 21, in __init__
    Wall(ursina.Vec3(6, y, 0))
  File "C:\Users\Bart\Documents\git\UrsinaFPS\game\map.py", line 14, in __init__
    self.texture.filtering = None
AttributeError: 'NoneType' object has no attribute 'filtering'
```

Any idea how I can fix this?

**Comment by barthogenes** [comment]
Putting the `model` assignment above the `texture` assignment in `game/map.py` fixed the issue for me:
![image](https://user-images.githubusercontent.com/20557666/125830612-f9d3c127-2884-4ee3-95be-41f570e60fde.png)

**Comment by MysteryCoder456** [comment]
I've pushed a commit implementing the fix you've shown.
